#!/usr/bin/env bash
#The script is displaying numbers from 1 to 100
for _ in {1..100}; do
  if (( _ % 3 == 0 && _ % 5 == 0 )); then
    echo "FizzBuzz"
  elif (( _ % 3 == 0 )); then
    echo "Fizz"
  elif (( _ % 5 == 0 )); then
    echo "Buzz"
  else
    echo "$_"
  fi
done
