#!/usr/bin/env bash
#managing process
pid="/var/run/my_process.pid"
if [ "$1" = "start" ]; then
         ./manage_my_process &
         echo $! > "$pid"
         echo "manage_my_process started"
elif [ "$2" = "stop" ]; then
       kill "$(cat $pid)"
       rm -f "$pid"
       echo "manage_my_process stopped"
elif [ "$3" = "restart" ]; then
       Kill "$(cat $pid)"
       rm -f "$pid"
       ./
